name: build

on: [push]

jobs:
  build:
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11"]
        target: ["macos-latest", "windows-latest"]

    runs-on: ${{ matrix.target }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install -U pip setuptools
          python -m pip install build

      - name: Build the package
        run: python -m build

      - name: Upload wheels
        uses: actions/upload-artifact@v3
        with:
          name: format('ca-whl-{0}-{1}', matrix.python-version, matrix.target)
          path: dist/*.whl

      - name: Upload zip source dist
        if: matrix.python-version == '3.11' && matrix.target == 'windows-latest'
        uses: actions/upload-artifact@v3
        with:
          name: "ca-sdist-zip"
          path: dist/*.tar.gz

      - name: Upload tar source dist
        if: matrix.python-version == '3.11' && matrix.target == 'macos-latest'
        uses: actions/upload-artifact@v3
        with:
          name: "ca-sdist-tar-gz"
          path: dist/*.tar.gz
