name: build

on: [push]

buildcore: &buildcore
  strategy:
    matrix:
      python-version: ["3.9", "3.10", "3.11"]

  steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install -U pip setuptools
        python -m pip install build

    - name: Build the package
      run: python -m build

jobs:
  build-win:
    runs-on: windows-latest
      <<: *buildcore

  build-mac:
    runs-on: macos-latest
    <<: *buildcore
