name: build-manylinux

on: [push]

jobs:
  build:
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11"]

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install -U pip setuptools
          python -m pip install build

      - name: Build the package
        run: python -m build

      - name: Upload wheels
        uses: actions/upload-artifact@v3
        with:
          path: dist/*.whl
